# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Cuesta
email: davidcuestamerino@gmail.com
description:  I am a curious, creative and well skilled software engineer which
              main fields of interests are data analysis, distributed systems,
              Big Data architectures, machine learning and time series analysis.
              My experienced is focused on the back-end. I love my profession
              and my main motivation is to solve problems using technical
              solutions. I really like working with different programming
              languages and deal with its advantages and disadvantages but my
              favourite one is Python.
url: "https://dcuestam.github.io" # the base hostname & protocol for your site
github_username:  dcuestam

# Build settings
markdown: kramdown
